### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by trallard** [trallard/Coding-foundation#3]
All ideas welcome, including sketches

Requirements:

- Must be a vector graphic. Design in any package you want, but ensure to provide exports in the following formats:
       - SVG
       - PNG
- Bonus points:
        - With "Coding foundation" text
        - without "Coding foundation" text
        - multiple sizes
        - multiple shapes - e.g. long thin landscape rectangle, square for icons, etc.

If you're interested in this task, I'd suggest discussing your idea or sharing a mock / sketch first to make sure we're on the same wavelength

All suitable designs will become stickers & be sent to contributors for free 🎉

**Comment by larissanv** [comment]
Hello!
So, I did this logo. Is something like that you're looking for?
I can change if you want to.

![logo](https://user-images.githubusercontent.com/17404587/31817364-61ff6cee-b572-11e7-9712-bc8d46e7d22b.png)

**Comment by trallard** [comment]
Thanks a lot :grinning: It is a nice concept although would it be possible to make the rainbow slightly bigger and include something (don't know exactly what) pointing to coding/programming 

If none of this makes sense let me know

**Comment by mbruckert** [comment]
What about This:

![coding_foundation](https://user-images.githubusercontent.com/18492311/31855671-e813c4ea-b67d-11e7-8612-85b9a1b8cdfd.png)

**Comment by trallard** [comment]
Hi @mbruckert thanks a lot! 🙌🏼 I like this ... is there any chance to have an extra version with the "Coding foundation" text somewhere??

**Comment by mbruckert** [comment]
@trallard I will have it done sometime today probably...
